### ISSUE TITLE
When to support grails 3.3?

### ISSUE THREAD

**Issue by kevinclcn** [grails-plugins/grails-database-migration#141]
### Steps to Reproduce

Per this link https://github.com/grails/gorm-hibernate5/issues/25, the correct multiple datasources config syntax for grails 3.3 is:
```
dataSource:
    # primary dataSource config ("dataSource")
dataSources:
    secondary:
        # secondary dataSource config ("dataSource_secondary")
```

rather than:

```
dataSources:
    dataSource:
        # primary dataSource config ("dataSource")
    secondary:
        # secondary dataSource config ("dataSource_secondary")
```

But the grails-database-migration tool supports only the second format. I've tried to provide a PR for quick fix, but it broken lots of tests since grails 3.3's test framework has been changed totally. https://github.com/grails-plugins/grails-database-migration/pull/140
