### ISSUE TITLE
dbm-gorm-diff not update DATABASECHANGELOG and not update "file.groovy"

### ISSUE THREAD

**Issue by adrianosaaquino** [grails-plugins/grails-database-migration#45]
Using grails 3.0.11, grails-database-migration 2.0.0.RC1 and java version "1.7.0_72".

When execute "$ grails dbm-gorm-diff add_autho.groovy --add" generate empty file and create table.

Steps:
```
$ grails create-app demo-grails-migration
$ cd demo-grails-migration
```

File "build.gradle":

Add:
```
buildscript {
    dependencies {
    ...
        classpath 'org.grails.plugins:database-migration:2.0.0.RC1'
    }
}
```

```
dependencies {
    ...
    runtime 'org.grails.plugins:database-migration:2.0.0.RC1'
    runtime 'mysql:mysql-connector-java:5.1.29'
}
```

And sourceSets:

```
sourceSets {
    main {
        resources {
            srcDir 'grails-app/migrations'
        }
    }
}
```

Execute
```
$ grails dbm-generate-changelog changelog.groovy
```

File "grails-app/migration/changelog.groovy" created successful. [OK]

Config database:

"grails-app/conf/application.yml"

```
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: root
    password: root..
environments:
    development:
        dataSource:            
            url: jdbc:mysql://localhost/demo
```

Now

```
$ grails dbm-update
```

After this command, table DATABASECHANGELOG and DATABASECHANGELOGLOCK are created in database with success. [OK]

```
$ grails create-domain-class demo.Author
```

Add some fields

```
package demo

class Author {
    
    String name
    Integer age

    static constraints = {
    }
}
```

```
$ grails dbm-gorm-diff add_autho.groovy --add 
```
After command "dbm-gorm-diff":

New entry in "grails-app/migration/changelog.groovy" [OK]
File "grails-app/migrations/add_author.groovy" created but is empty. [NOK]
Table author has been created [NOK].
Table DATABASECHANGELOG is empty [OK].

In grails 2.2.4 and database-migration:1.3.8, after execute 

```
$ grails dbm-gorm-diff add_autho.groovy --add 
```

File "add_autho.groovy" has data to update database and table do not exist in database, run dbm-update, line is generate in DATABASECHANGELOG and table is created.
